repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        pass_filenames: false
        entry: poetry run black ./

      - id: isort
        name: isort
        pass_filenames: false
        language: python
        entry: poetry run isort ./

      - id: ruff
        name: ruff
        language: python
        pass_filenames: false
        entry: poetry run ruff ./
        args:
          - --fix
