[tool.poetry]
name = "AIAS"
version = "1.3"
description = "AIAS (Artifical Intelligence AntiSpam) is an open-source Discord bot that has innovative moderation features, such as nextgen word filter and AI-based spam detection."
authors = ["Exenifix"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
disnake = "^2.5.1"
python-dotenv = "^0.20.0"
scikit-learn = "^1.1.1"
exencolorlogs = "^1.0.2"
psutil = "^5.9.1"
asyncpg = "^0.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
