name: Pylint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry install
          poetry add pylint
      - name: Analysing the code with pylint
        run: |
          poetry run pylint $(git ls-files '*.py') --exit-zero --disable=missing-module-docstring,missing-function-docstring,missing-class-docstring,no-self-use,too-few-public-methods,bare-except
