name: Docker Runner

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    environment: production
    env:
      TOKEN: ${{ secrets.TOKEN }}
      DATABASE: ${{ secrets.DATABASE }}
      HOST: 127.0.0.1
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TOPGG_TOKEN: ${{ secrets.TOPGG_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t aias .
        
      - name: Kill Previous Container
        continue-on-error: true
        run: docker rm -f aias
        
      - name: Run Container
        run: docker run -d --name aias --net=host -e TOKEN=$TOKEN -e DATABASE=$DATABASE -e HOST=$HOST -e USER=$USER -e PASSWORD=$PASSWORD -e TOPGG_TOKEN=$TOPGG_TOKEN aias:latest
