name: Docker Runner

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    environment: production
    env:
      TOKEN: ${{ secrets.TOKEN }}
      DATABASE: ${{ secrets.DATABASE }}
      HOST: 127.0.0.1
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TOPGG_TOKEN: ${{ secrets.TOPGG_TOKEN }}
      IPQS_APIKEY: ${{ secrets.IPQS_APIKEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker-compose up -d --build

      - name: Display Bot Logs
        run: python3 -m exendlr aias "bot is ready!"

      - name: Cleanup Unused Images
        run: docker image prune -f
